version: '3.9'

services:

    web:
        build:
            context: .
            dockerfile: docker/web/Dockerfile
            args:
                - APP_PHP_VERSION=${APP_PHP_VERSION}
        container_name: ${APP_NAME}-web
        ports:
            - ${APP_PORT}:80
            - ${APP_PORT_SSL}:443
        working_dir: /var/www/html
        environment:
            - TZ=${APP_TZ}
        volumes:
            - ./:/var/www/html
            - ./docker/web/apache2/sites-available:/etc/apache2/sites-available
            - ./docker/web/apache2/ssl:/etc/apache2/ssl
            - ./docker/web/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
            - ./docker/web/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

    workspace:
        build:
            context: .
            dockerfile: docker/workspace/Dockerfile
            args:
                - APP_PHP_VERSION=${APP_PHP_VERSION}
        container_name: ${APP_NAME}-workspace
        working_dir: /var/www/html
        environment:
            - TZ=${APP_TZ}
        volumes:
            - ./:/var/www/html

    db:
        image: mariadb:10.5.9
        container_name: ${APP_NAME}-db
        hostname: ${DB_HOSTNAME}
        restart: always
        ports:
            - ${APP_DB_PORT}:3306
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - TZ=${APP_TZ}
        volumes:
            - ./db/mariadb:/var/lib/mysql
            - ./docker/db/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf

    pma:
        image: phpmyadmin/phpmyadmin
        container_name: ${APP_NAME}-pma
        ports:
            - ${APP_PMA_PORT}:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=db
        volumes:
            - ./docker/pma/config.php:/etc/phpmyadmin/config.user.inc.php
            - ./docker/pma/themes/boodark:/var/www/html/themes/boodark

    mailhog:
        image: mailhog/mailhog
        container_name: ${APP_NAME}-mailhog
        restart: always
        logging:
            driver: 'none'
        ports:
            - ${MAILHOG_HTTP_PORT}:8025
            - ${MAILHOG_SMTP_PORT}:1025
